/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.airline.management.system;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pradeep John
 */
public class FlightType extends javax.swing.JFrame {
DefaultTableModel model1;
DefaultTableModel model2;
    /**
     * Creates new form home
     
     */
    public FlightType() {
        initComponents();
        
         model1= (DefaultTableModel)table1.getModel();
         model2= (DefaultTableModel)table2.getModel();
    }
    public FlightType(String custid) {
        initComponents();

         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rb11 = new javax.swing.JRadioButton();
        rb22 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lufthansa Flights- Flight Reservation");
        setResizable(false);

        buttonGroup1.add(rb11);
        rb11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rb11.setText("International Flight");
        rb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb11ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb22);
        rb22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rb22.setText("Domestic Flight");
        rb22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb22ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/airline/management/system/international.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/airline/management/system/domestic.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "From", "To", "Price", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1);

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "From", "To", "Price", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table2);

        jButton1.setText("Book Flight");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Flight Reservation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb22)
                    .addComponent(rb11)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButton2)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(rb11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rb22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(19, 19, 19))
        );

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(835, 537));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb11ActionPerformed
model1.insertRow(model1.getRowCount(),new Object[]{"Trivandrum", "Bali", "21485", "06:20"});  
model1.insertRow(model1.getRowCount(),new Object[]{"Trivandrum", "Bangkok", "9000", "20:45"});
model1.insertRow(model1.getRowCount(),new Object[]{"Trivandrum", "Cairo", "22975", "10:25"});
model1.insertRow(model1.getRowCount(),new Object[]{"Trivandrum", "CapeTown", "42500", "16:45"});
model1.insertRow(model1.getRowCount(),new Object[]{"Trivandrum", "Chicago", "35000", "06:30"});
model1.insertRow(model1.getRowCount(),new Object[]{"Trivandrum", "Dubai", "12000", "08:15"});
model1.insertRow(model1.getRowCount(),new Object[]{"Trivandrum", "Frankfurt", "18500", "06:50"});
model1.insertRow(model1.getRowCount(),new Object[]{"Trivandrum", "HongKong", "20845", "12:00"});
model1.insertRow(model1.getRowCount(),new Object[]{"Trivandrum", "Istanbul", "22000", "10:45"});
model1.insertRow(model1.getRowCount(),new Object[]{"Trivandrum", "London", "22600", "14:35"});
model1.insertRow(model1.getRowCount(),new Object[]{"Trivandrum", "LosAngeles", "35000", "22:00"});
model1.insertRow(model1.getRowCount(),new Object[]{"Trivandrum", "Melbourne", "27800", "21:15" });
model1.insertRow(model1.getRowCount(),new Object[]{"Trivandrum", "New York", "32000", "08:50"});
model1.insertRow(model1.getRowCount(),new Object[]{"Trivandrum", "Paris", "18500", "18:45"});
model1.insertRow(model1.getRowCount(),new Object[]{"Trivandrum", "Rome", "19900", "20:00"});
model1.insertRow(model1.getRowCount(),new Object[]{"Trivandrum", "SanFrancisco", "35000", "12:00"});
model1.insertRow(model1.getRowCount(),new Object[]{"Trivandrum", "shanghai", "24430", "10:15" });
model1.insertRow(model1.getRowCount(),new Object[]{"Trivandrum", "Singapore", "9000", "21:10" });
model1.insertRow(model1.getRowCount(),new Object[]{"Trivandrum", "Sydney", "27800", "12:00"});
model1.insertRow(model1.getRowCount(),new Object[]{"Trivandrum", "Toronto", "35000", "17:00 "});         // TODO add your handling code here:
    }//GEN-LAST:event_rb11ActionPerformed

    private void rb22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb22ActionPerformed
model2.insertRow(model2.getRowCount(),new Object[]{"Trivandrum", "Bangalore", "3125", "16:30"}); 
     model2.insertRow(model2.getRowCount(),new Object[]{"Trivandrum", "Chennai ", "3225", "19:00" });
     model2.insertRow(model2.getRowCount(),new Object[]{"Trivandrum", "Delhi", "1425 ", "08:30"});
     model2.insertRow(model2.getRowCount(),new Object[]{"Trivandrum", "Goa", "1025 ", "09:50"});
     model2.insertRow(model2.getRowCount(),new Object[]{"Trivandrum", "Hyderabad", "1525", "11:00"});
     model2.insertRow(model2.getRowCount(),new Object[]{ "Trivandrum", "Kolkata", "3825 ", "05:30"});
     model2.insertRow(model2.getRowCount(),new Object[]{"Trivandrum", "Lucknow", "3025 ", "05:30"});
     model2.insertRow(model2.getRowCount(),new Object[]{"Trivandrum", "Mumbai", "1725", "12:00"});
     model2.insertRow(model2.getRowCount(),new Object[]{"Trivandrum", "Vishakapatnam", "3725", "19:00"});
     model2.insertRow(model2.getRowCount(),new Object[]{"Trivandrum", "Pune", "3725", "9:00"});         // TODO add your handling code here:
    }//GEN-LAST:event_rb22ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.hide();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           
           try
            {
               
                if(rb11.isSelected()) {new CustomerDetails("International").setVisible(true);}
                 else 
                   if(rb22.isSelected()) {new CustomerDetails("Domestic").setVisible(true);}
                   else
                      JOptionPane.showMessageDialog(null, "Select either international or domestic flight option"); 
               

            }catch(Exception e)
            { JOptionPane.showMessageDialog(this, e.getMessage());}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightType().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rb11;
    private javax.swing.JRadioButton rb22;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables
}
